[package]

name = "retag"
version = "0.0.1"
authors = ["Michael Maurizi <michael.maurizi@gmail.com>"]

[dependencies]
glob = "0.2"
tempdir = "0.3"
docopt = "0.6"
rustc-serialize = "0.3"
toml = "0.1"
notify = "2.4"
