[package]

name = "retag"
version = "0.0.1"
authors = ["Michael Maurizi <michael.maurizi@gmail.com>"]

[dependencies]
glob = "0.2"
tempdir = "0.3.2"
docopt = "*"
rustc-serialize = "*"
toml = "0.1.19"

[dependencies.notify]
git = "https://github.com/maurizi/rsnotify"
